name: Build and Test (Reusable)
on: 
  workflow_call: # Allow other workflows to call this one

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

          # Frontend build
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'app/frontend/package-lock.json'
          working-directory: './app/frontend'
      
      - name: Install frontend dependencies
        run: npm install
        working-directory: './app/frontend'
      
      - name: Build frontend
        run: npm run build
        working-directory: './app/frontend'
      
      # Backend build
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install -r ./requirements_ai.txt
      

      - name: Run frontend tests
        run: |
          npm test || echo "No frontend tests found or tests failed."
        working-directory: './app/frontend'

      - name: Run backend tests
        run: |
          python -m pytest || echo "No backend tests found or tests failed."
        working-directory: './'


